[package]
name = "mold"
version = "0.1.0"
authors = ["John Weachock <jweachock@gmail.com>"]
edition = "2018"

[dependencies]
base64 = "0.10.1"
clap = "2.33.0"
colored = "1.8"
env_logger = "0.6.1"
exitcode = "1.1.2"
exitfailure = "0.5.1"
failure = "0.1.5"
git2 = "0.8.0"
indexmap = "1.0.2"
log = "0.4.6"
serde = "1.0.92"
serde_derive = "1.0.92"
structopt = "0.2.16"
toml = "0.5.1"
serde_yaml = "0.8.9"

[[bin]]
name = "mold"
path = "src/main.rs"
